package com.mycompany.app.Sticker;

import com.mycompany.app.Sticker.FourDigitCodeGenerator.FourDigitCode;

/**
 * Generates a {@link Sticker}.
 *
 * @author Kevin Forst
 */
public class StickerGenerator {
	private final Sticker sticker;

	/**
	 * Returns the {@link Sticker} generated by this StickerGenerator.
	 * 
	 * @return the {@link Sticker} generated by this StickerGenerator.
	 */
	public Sticker getSticker() {
		return sticker;
	}

	/**
	 * Constructs a StickerGenerator with the specified content.
	 * 
	 * @param content the content to be encoded in the QR code.
	 */
	public StickerGenerator(String content) {
		this.sticker = new Sticker(content);
	}

	/**
	 * Represents a sticker containing a {@link QRCodeGenerator} and a {@link FourDigitCode}.
	 *
	 * @author Kevin Forst
	 */
	public class Sticker {
		private final QRCodeGenerator qrCodeGenerator;
		private final FourDigitCode code;

		/**
		 * Returns the {@link QRCodeGenerator} of this sticker.
		 * 
		 * @return the {@link QRCodeGenerator} of this sticker.
		 */
		public QRCodeGenerator getQrCodeGenerator() {
			return qrCodeGenerator;
		}

		/**
		 * Returns the {@link FourDigitCode} of this sticker.
		 * 
		 * @return the {@link FourDigitCode} of this sticker.
		 */
		public FourDigitCode getFourDigitCode() {
			return code;
		}

		/**
		 * Constructs a Sticker with the specified content.
		 * 
		 * @param content the content to be encoded in the QR code.
		 */
		Sticker(String content) {
			this.qrCodeGenerator = new QRCodeGenerator(content);
			this.code = new FourDigitCodeGenerator().newCode();
		}
	}
}
